framework:
    cache:
        # Use Redis when available, filesystem as fallback
        app: '%env(default:cache.adapter.filesystem:REDIS_CACHE_DSN)%'
        
        # Redis configuration
        pools:
            cache.redis:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_CACHE_DSN)%'

when@prod:
    framework:
        cache:
            app: cache.redis
            pools:
                cache.redis:
                    adapter: cache.adapter.redis
                    provider: '%env(REDIS_CACHE_DSN)%'