framework:
    cache:
        prefix_seed: 'wowmanager'
        
        # Simple and reliable approach - let Symfony handle the fallback
        app: cache.adapter.redis
        default_redis_provider: '%env(default::REDIS_CACHE_DSN)%'

        pools:
            # Dedicated pools for different types of data
            cache.user_sessions:
                adapter: cache.adapter.redis
                provider: '%env(default::REDIS_CACHE_DSN)%'
                default_lifetime: 7200
                
            cache.messages:
                adapter: cache.adapter.redis
                provider: '%env(default::REDIS_CACHE_DSN)%'
                default_lifetime: 6000

when@dev:
    framework:
        cache:
            # Development: filesystem for simplicity
            app: cache.adapter.filesystem
            # Override pools to use filesystem in dev
            pools:
                cache.user_sessions:
                    adapter: cache.adapter.filesystem
                cache.guild_data:
                    adapter: cache.adapter.filesystem  
                cache.auction_data:
                    adapter: cache.adapter.filesystem

when@test:
    framework:
        cache:
            app: cache.adapter.array
            pools:
                cache.user_sessions:
                    adapter: cache.adapter.array
                cache.guild_data:
                    adapter: cache.adapter.array
                cache.auction_data:
                    adapter: cache.adapter.array