# config/packages/framework.yaml
framework:
    session:
        handler_id: '%env(SESSION_HANDLER_ID)%'
        save_path: '%env(SESSION_SAVE_PATH)%'
        cookie_secure: auto
        cookie_samesite: lax