services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Upload directory configuration
    app.upload_directory:
        class: string
        factory: ['Symfony\Component\DependencyInjection\EnvVarProcessor', 'getEnv']
        arguments: ['string:UPLOAD_PATH']

    # Redis session handler for production
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    # Redis client
    Redis:
        class: Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_URL)%'
    # Redis session handler
    app.session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@app.redis.session'
            
    # Redis connection for sessions
    app.redis.session:
        class: Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(REDIS_SESSION_DSN)%'
            - { retry_interval: 2, read_timeout: 10 }            